In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]
x=np.array(l)
print(x)

[1 2 3 4]


In [3]:
type(x)

numpy.ndarray

In [6]:
y=np.array([[1,2,3,4],[2,3,4,5]])
print(y)
print(type(y))

[[1 2 3 4]
 [2 3 4 5]]
<class 'numpy.ndarray'>


In [7]:
x.ndim

1

In [8]:
y.ndim

2

In [10]:
np.matrix(x)#matrix always 2 dimension but array may be 1 or 2 dimension

matrix([[1, 2, 3, 4]])

In [11]:
np.asanyarray(y)#convert to array

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [12]:
a=np.array([1,2,3,4])
x=a
print(a)
print(x)
a[0]=5
print(a)
print(x)

[1 2 3 4]
[1 2 3 4]
[5 2 3 4]
[5 2 3 4]


In [13]:
a=np.array([1,2,3,4])
x=a
print(a)
print(x)
x[0]=5
print(a)
print(x)

[1 2 3 4]
[1 2 3 4]
[5 2 3 4]
[5 2 3 4]


In [14]:
a=np.array([1,2,3,4])
x=np.copy(a)
print(a)
print(x)
x[0]=5
print(a)
print(x)

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[5 2 3 4]


In [15]:
np.fromfunction(lambda i,j:i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [16]:
np.fromfunction(lambda x,y:x*y,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [17]:
np.fromstring("23,23,24,25,25",sep=",")

array([23., 23., 24., 25., 25.])

In [18]:
a.size#total element

4

In [19]:
a.shape#rows and column

(4,)

In [22]:
a.dtype

dtype('int32')

In [23]:
list(range(9))#only support int value

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [24]:
np.arange(1,8)

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
np.arange(1,8,2)

array([1, 3, 5, 7])

In [26]:
np.arange(1.2,7.2)

array([1.2, 2.2, 3.2, 4.2, 5.2, 6.2])

In [30]:
np.linspace(1,8,45)#divide eually 45 times between 1 to 8

array([1.        , 1.15909091, 1.31818182, 1.47727273, 1.63636364,
       1.79545455, 1.95454545, 2.11363636, 2.27272727, 2.43181818,
       2.59090909, 2.75      , 2.90909091, 3.06818182, 3.22727273,
       3.38636364, 3.54545455, 3.70454545, 3.86363636, 4.02272727,
       4.18181818, 4.34090909, 4.5       , 4.65909091, 4.81818182,
       4.97727273, 5.13636364, 5.29545455, 5.45454545, 5.61363636,
       5.77272727, 5.93181818, 6.09090909, 6.25      , 6.40909091,
       6.56818182, 6.72727273, 6.88636364, 7.04545455, 7.20454545,
       7.36363636, 7.52272727, 7.68181818, 7.84090909, 8.        ])

In [31]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [32]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.zeros((3,4,2))#3 meand dimension and (4,2) represents rows and column

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [38]:
np.zeros((4,3,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [41]:
x=np.ones((2,3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
x+5

array([[6., 6., 6.],
       [6., 6., 6.]])

In [46]:
arr1=np.empty((2,3))
arr1

array([[6., 6., 6.],
       [6., 6., 6.]])

In [47]:
np.eye(5)
#The np.eye function in NumPy is used to create a 2-D identity matrix with ones on the diagonal and zeros elsewhere

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
np.random.rand(2,4)

array([[0.0444797 , 0.22291376, 0.91124466, 0.72446516],
       [0.81979042, 0.58838861, 0.89603314, 0.35627878]])

In [51]:
np.random.randn(2,4)#mean is 0 and SD is 1

array([[ 1.77677023, -0.50441365, -1.18495339,  0.75639842],
       [ 0.28041842, -0.13608767,  0.97069781, -0.8933962 ]])

In [52]:
np.random.randint(1,5,(2,6))

array([[2, 1, 3, 1, 4, 3],
       [1, 2, 3, 2, 2, 1]])

In [56]:
x=np.arange(1,13).reshape(4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [57]:
x>10

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True,  True]])

In [58]:
x[x>10]

array([11, 12])

In [59]:
x[0]

array([1, 2, 3])

In [61]:
x[0,[0,1]]

array([1, 2])

In [66]:
x[1:3,[0,1]]

array([[4, 5],
       [7, 8]])

In [70]:
arr1=np.random.randint(1,5,(4,4))
arr2=np.random.randint(1,9,(4,4))
print(arr1)
print(arr2)

[[2 2 4 4]
 [2 2 1 2]
 [3 1 1 4]
 [2 3 1 3]]
[[4 7 4 8]
 [1 8 2 8]
 [2 4 4 5]
 [8 8 8 4]]


In [71]:
arr1+arr2

array([[ 6,  9,  8, 12],
       [ 3, 10,  3, 10],
       [ 5,  5,  5,  9],
       [10, 11,  9,  7]])

In [72]:
arr1-arr2

array([[-2, -5,  0, -4],
       [ 1, -6, -1, -6],
       [ 1, -3, -3, -1],
       [-6, -5, -7, -1]])

In [73]:
arr1.dot(arr2)


array([[50, 78, 60, 68],
       [28, 50, 32, 45],
       [47, 65, 50, 53],
       [37, 66, 42, 57]])

In [74]:
arr1.T

array([[2, 2, 3, 2],
       [2, 2, 1, 3],
       [4, 1, 1, 1],
       [4, 2, 4, 3]])

In [75]:
arr1@arr2

array([[50, 78, 60, 68],
       [28, 50, 32, 45],
       [47, 65, 50, 53],
       [37, 66, 42, 57]])

In [76]:
arr1/0

C:\Users\adity\AppData\Local\Temp\ipykernel_20540\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [77]:
arr1.flatten()

array([2, 2, 4, 4, 2, 2, 1, 2, 3, 1, 1, 4, 2, 3, 1, 3])

In [78]:
np.expand_dims(arr1,axis=0)

array([[[2, 2, 4, 4],
        [2, 2, 1, 2],
        [3, 1, 1, 4],
        [2, 3, 1, 3]]])

In [79]:
data=np.array([[1],[2],[3]])
np.squeeze(data)

array([1, 2, 3])

In [80]:
np.repeat(data,5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [82]:
x=np.array(["adi","abc"])
x

array(['adi', 'abc'], dtype='<U3')

In [83]:
np.char.upper(x)

array(['ADI', 'ABC'], dtype='<U3')

In [85]:
np.char.title(x)

array(['Adi', 'Abc'], dtype='<U3')

In [86]:
np.sin(arr1)

array([[ 0.90929743,  0.90929743, -0.7568025 , -0.7568025 ],
       [ 0.90929743,  0.90929743,  0.84147098,  0.90929743],
       [ 0.14112001,  0.84147098,  0.84147098, -0.7568025 ],
       [ 0.90929743,  0.14112001,  0.84147098,  0.14112001]])

In [87]:
np.cos(arr1)

array([[-0.41614684, -0.41614684, -0.65364362, -0.65364362],
       [-0.41614684, -0.41614684,  0.54030231, -0.41614684],
       [-0.9899925 ,  0.54030231,  0.54030231, -0.65364362],
       [-0.41614684, -0.9899925 ,  0.54030231, -0.9899925 ]])

In [88]:
np.power(arr1,2)

array([[ 4,  4, 16, 16],
       [ 4,  4,  1,  4],
       [ 9,  1,  1, 16],
       [ 4,  9,  1,  9]], dtype=int32)

In [89]:
np.median(arr1)

2.0

In [90]:
np.mean(arr1)

2.3125

In [91]:
np.std(arr1)

1.0439558180306292

In [92]:
np.var(arr1)

1.08984375

In [96]:
arr=np.array([34,56,32,2,45,98,3,4,5,89,0])

In [97]:
np.sort(arr)

array([ 0,  2,  3,  4,  5, 32, 34, 45, 56, 89, 98])

In [98]:
np.searchsorted(arr,6)

0

In [99]:
np.count_nonzero(arr)

10

In [100]:
np.where(arr>7)

(array([0, 1, 2, 4, 5, 9], dtype=int64),)

In [101]:
np.extract(arr>9,arr)

array([34, 56, 32, 45, 98, 89])

In [102]:
arr.byteswap()

array([ 570425344,  939524096,  536870912,   33554432,  754974720,
       1644167168,   50331648,   67108864,   83886080, 1493172224,
                0])

In [104]:
arr.view()

array([34, 56, 32,  2, 45, 98,  3,  4,  5, 89,  0])

In [105]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out